//tag::ref-doc[]
= Scripable Transform Processor

A *Spring Cloud Stream* module that transforms messages using a script. The script body is supplied directly
as a property value. The language of the script can be specified (groovy/javascript/ruby/python).

== Input

=== Headers

N/A

=== Payload

* Any

== Output

=== Headers

N/A

=== Payload

* Any

== Options

The **$$scriptable-transform$$** $$processor$$ has the following options:

//tag::configuration-properties[]
$$scriptable-transformer.language$$:: $$Language of the text in the script property. Supported: groovy, javascript, ruby, python.$$ *($$String$$, default: `$$<none>$$`)*
$$scriptable-transformer.script$$:: $$Text of the script.$$ *($$String$$, default: `$$<none>$$`)*
$$scriptable-transformer.variables$$:: $$Variable bindings as a new line delimited string of name-value pairs, e.g. 'foo=bar\n baz=car'.$$ *($$Properties$$, default: `$$<none>$$`)*
$$scriptable-transformer.variables-location$$:: $$The location of a properties file containing custom script variable bindings.$$ *($$Resource$$, default: `$$<none>$$`)*
//end::configuration-properties[]

== Build

```
$ ./mvnw clean install -PgenerateApps
$ cd apps
```
You can find the corresponding binder based projects here.
You can then `cd` into one one of the folders and build it:
```
$ ./mvnw clean package
```
Folder `target` will then contain generated jars (_original_, _repackaged_ also known as _**executable** jar_, with _javadoc_, etc.) of which the _executable_ jar can be used directly with `java` to run the application.

Name of executable jar follows the pattern:
`scriptable-transform-processor-`**BINDER**`-`**VERSION**`.jar`


== Examples

Starting from top-level folder, assuming you target rabbitmq and your `pom.xml` has `2.1.0.RELEASE` for the `project.version` property, you can build and run the standalone application with :

```
$ ./mvnw clean install -PgenerateApps
$ cd apps/scriptable-transform-processor-rabbit
$ ./mvnw clean package
$ java -jar target/scriptable-transform-processor-rabbit-2.1.0.RELEASE.jar --scriptable-transformer.language=ruby --scriptable-transformer.script="return ""#{payload.upcase}"""
```

//end::ref-doc[]

